Fix Linking Issues (Undefined reference to symbols)
- change verilog include path to: /usr/local/share/verilator/include
  that's the default path when installing verilator using the
  git quick install method
  (see: https://veripool.org/guide/latest/install.html)

- instead of directly using .a file as a linker source (which caused
  linking errors), we now use it as a library that needs to be linked
  to other object files using the "-l" syntax. since running make in
  obj_dir doesnt generate .a file eith a lib prefix, we have to provide
  the full name of the library prefixed by a ':' character.
    eg: $ gcc ...  -l:VAtomBones__ALL.a